version: '3'
services:
  app:
    build: .
    ports:
      - "9080:9080"
    depends_on:
      - mypostgres
  mypostgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
